namespace: a10
name: acos_cli
version: 3.0.0
readme: README.md
authors:
    - "support@a10networks.com"
    - "smundhe-a10"
description: Collection of modules used to configure ACOS devices over SSH
license:
- GPL-2.0-or-later
tags: [acos, networking]

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies:
  "ansible.netcommon": ">=3.0.0,<=6.0.0"

# The URL of the originating SCM repository
repository: https://github.com/a10networks/a10-acos-cli

# The URL to any online docs
documentation: https://github.com/a10networks/a10-acos-cli/blob/master/README.md
